// This file is generated by Slice Machine. Update with care!

import CallToAction from './CallToAction';
import Popup from './Popup';
import SectionTitle from './SectionTitle';
import Slider from './Slider';
import Test01 from './Test01';
import Test02 from './Test02';
import Test03 from './Test03';

export {
	CallToAction,
	Popup,
	SectionTitle,
	Slider,
	Test01,
	Test02,
	Test03,
};

export const components = {
	call_to_action: CallToAction,
	popup: Popup,
	section_title: SectionTitle,
	slider: Slider,
	test01: Test01,
	test02: Test02,
	test03: Test03,
};
