// This file is generated by Slice Machine. Update with care!

import CallToAction from './CallToAction';
import SectionTitle from './SectionTitle';
import Slider from './Slider';

export {
	CallToAction,
	SectionTitle,
	Slider,
};

export const components = {
	call_to_action: CallToAction,
	section_title: SectionTitle,
	slider: Slider,
};
